### ISSUE TITLE
make an hmac function to be used in ethereum/lib/MerkleTreeAttestation.sol

### ISSUE THREAD

**Issue by colourful-land** [alpha-wallet/blockchain-attestation#10]
Since Solidity 0.4.3 `keccak256` is supported, which consumes half of the gas of `sha256`. `keccak256` is Ethereum-SHA-3 which is not SHA3. Be careful about solidity's `sha3()` function which is just an alias of `keccak256()`. Ethereum transactions are summarised with a MerkleTree in `keccak256`.

`sha256` uses 60 gas + 12 gas for each word (rounded up) for input data to a SHA2-256 operation. From Ethereum Yellowpaper†. Without looking into details I suspect it's because `sha256` is implemented as so-called precompiled contracts.

We can leave this decision to the attestation issuer but I feel that it will be a bad idea.

# consistence argument

There are two reasons to consider using `sha256` instead of `keccak256`. First, for Bitcoin there is no support for keccak256 and a future new public blockchain may choose not to support it, but their own hash function. Second, Vitalik intended keccak256 to be ASIC-mining resistant for a few years and he achieved it; we don't pursue the same goal because an attestation isn't mined. 

# price argument

Ethereum apparently overextended and want `keccak256` to be the standard in non-mining cases too. They made a huge incentive for us to comply - it's half price.‡

A Merkle tree with 16 levels can hold 65536 attributes, might be enough for a typical attestation without negative predicates (e.g. if you have a residential address in Australia you will have a residential address not in US, not in China, not in Singapore... etc, roughly 256 predicates).

The gas consumption for `sha256()` for a test of a single attribute (or predicate) will cost:

15 times hash, each with 60 gas for the call and 12×2 gas for 2 words - *assuming each word is a `byte32`, verify this later* -  making up 84 gas.
Plus:
1 hash with 60 gas for the call and 12*3 gas for 3 words (key, value, hash-key)

1356 gas in total, not counting the for..loop that might be involved.

Gas price is 2 gwei for now but it reached more than 100 gwei a few weeks ago. So the cost is 1356×2 or 1356×100 gwei. At the peak a Finney is worth 1USD, making the cost between 0.002USD and 0.1356USD. Consider ICO might be the cause of congestion, and ICO is a typical use-case of attestation, the combination forbodes expensive consequence.

# keyed hash

It seems Ethereum does not provide a keyed hash function like hmac. In the above calculation we used the concatenation of hash-key and data. Does the need of keyed hash influnce our choice?

† https://github.com/ethereum/yellowpaper

‡ https://ethereum.stackexchange.com/questions/3184/what-is-the-cheapest-hash-function-available-in-solidity

**Comment by colourful-land** [comment]
@James-Sangalli you mentioned that since sha256 is implemented as smart-contract code, we may as well use libraries like safemath. Can you dig around to see if they support hmac? Thanks.

**Comment by jot2re** [comment]
In regards to the keyed hash, it is easy and "cheap" to implement HMAC using any hash function, as it just requires some xor operations with a static string and an extra call to [the hash function](https://en.wikipedia.org/wiki/HMAC). Simply taking the key concatenated with data is open for [an extension attack.](https://en.wikipedia.org/wiki/Length_extension_attack)

In regards to choice of hash function, I think both are good. SHA-256 is most mainstream though, but since this is an Ethereum context, Kaccek might make most sense. 

In regards to allowed both options I would recommend only using one. More options for the user means more ways things can go wrong. 

Finally note that counting levels in a Merkle tree starting with 1, means that a level 16 tree only has 2^15=32,768 attributes, as attributes are only contained in the leafs.

**Comment by colourful-land** [comment]
Play with it if you have the time - it should be quick. Otherwise, we will do it.

**Comment by lyhistory** [comment]
commited to branch lib/hmacsha256
I find someone has implemented it, made small changes, and tested, it seems working
![hmacsha256](https://user-images.githubusercontent.com/1522513/44957365-1ad9a000-af04-11e8-920e-67530b46f195.png)

**Comment by colourful-land** [comment]
@jot2re is there anything we should pay attention to in regards to standardization? say if there is a standard way to do hmac our computation result should be the same produced by other tools like `ssl`

**Comment by jot2re** [comment]
HMAC has a specific and formal specification. It is described I [RFC-2104](https://tools.ietf.org/html/rfc2104)
Unlike most RFC, this one is only 6 pages and actually readable :)

**Comment by colourful-land** [comment]
@jot2re there is a bit of performance degradation using hmac compare to the underlying hash, to my understanding, only the leaf nodes need to be hashed with a key, correct?

**Comment by jot2re** [comment]
I forgot to point out one important thing: Keccak is _not_ vulnerable to length extension attacks. So if _only_ Keccak is used it is actually not necessary to do HMAC, but H(key||message) should be sufficient. 
@colourful-land I must admit I have become a bit in doubt of what the key is when we use HMAC in the context of Merkle trees. As far as I remember, when we discussed the attestation, when did not consider HMAC for the actual tree construction? Maybe I am remembering something  wrong?

**Comment by James-Sangalli** [comment]
Handled but no longer needed
